services:
  - type: web
    name: my-django-app
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn bushiba:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"