services:
  - type: web
    name: bushiba
    env: python
    region: oregon
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: |
      daphne -b 0.0.0.0 -p $PORT bushiba.asgi:application
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: bushiba.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - fromDatabase:
          name: bushiba-db
          property: connectionString