# Generated by Django 5.0.4 on 2025-02-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('shool', models.CharField(max_length=64, verbose_name='学校')),
                ('level', models.SmallIntegerField(choices=[(1, 'Lv1'), (2, 'Lv2'), (3, 'Lv3'), (4, 'Lv4'), (5, 'Lv5')], default=1, verbose_name='等级')),
                ('sex', models.SmallIntegerField(choices=[(1, '男'), (0, '女')], verbose_name='性别')),
            ],
        ),
    ]
