# Generated by Django 5.0.4 on 2025-02-28 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bushiba_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=64, verbose_name='学校')),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='shool',
        ),
        migrations.AddField(
            model_name='users',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bushiba_app.school', verbose_name='学校'),
        ),
    ]
