# Generated by Django 5.0.4 on 2025-02-28 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bushiba_app', '0002_school_remove_users_shool_users_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school',
            field=models.CharField(max_length=128, verbose_name='学校'),
        ),
        migrations.AlterField(
            model_name='users',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bushiba_app.school', verbose_name='学校'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='发布时间')),
                ('demand', models.TextField(verbose_name='需求')),
                ('demand_image', models.ImageField(blank=True, null=True, upload_to='task_images/', verbose_name='需求图片')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='定价')),
                ('state', models.SmallIntegerField(choices=[(0, '未接单'), (1, '已接单'), (2, '已完成')], verbose_name='状态')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bushiba_app.users', verbose_name='发布人')),
            ],
        ),
    ]
