# Generated by Django 5.0.4 on 2025-02-28 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bushiba_app', '0003_alter_school_school_alter_users_school_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bushiba_app.school', verbose_name='学校'),
        ),
    ]
