# Generated by Django 5.0.4 on 2025-02-28 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bushiba_app', '0004_alter_users_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bushiba_app.school', verbose_name='学校'),
        ),
    ]
