# Generated by Django 5.0.4 on 2025-03-01 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bushiba_app', '0005_alter_users_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.SmallIntegerField(choices=[(0, '未接单'), (1, '已接单'), (2, '已完成')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='users',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bushiba_app.school', verbose_name='学校'),
        ),
    ]
