# Generated by Django 5.0.4 on 2025-03-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bushiba_app', '0006_alter_task_state_alter_users_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default=' ', max_length=128, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='task',
            name='demand_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/task_images/%Y/%m', verbose_name='需求图片'),
        ),
    ]
