# Generated by Django 5.0.4 on 2025-03-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bushiba_app', '0007_task_title_alter_task_demand_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='demand_image',
            field=models.ImageField(blank=True, null=True, upload_to='bushiba_app/static/media/task_images/%Y/%m', verbose_name='需求图片'),
        ),
    ]
