# Generated by Django 5.0.4 on 2025-03-04 10:27

import bushiba_app.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bushiba_app', '0008_alter_task_demand_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='demand',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='需求'),
        ),
        migrations.AlterField(
            model_name='task',
            name='demand_image',
            field=models.ImageField(blank=True, null=True, upload_to=bushiba_app.models.rename_image_task, verbose_name='需求图片'),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='发布时间')),
                ('text', models.TextField(validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='你想说什么')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bushiba_app.users', verbose_name='发布人')),
            ],
        ),
        migrations.CreateModel(
            name='Activity_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=bushiba_app.models.rename_image_activity, verbose_name='图片')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='bushiba_app.activity')),
            ],
        ),
    ]
