# Generated by Django 5.0.4 on 2025-03-07 02:34

import bushiba_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bushiba_app', '0009_alter_task_demand_alter_task_demand_image_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=bushiba_app.models.rename_image_activity, verbose_name='需求图片'),
        ),
        migrations.AddField(
            model_name='activity',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=bushiba_app.models.rename_image_activity, verbose_name='需求图片'),
        ),
        migrations.AddField(
            model_name='activity',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=bushiba_app.models.rename_image_activity, verbose_name='需求图片'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='text',
            field=models.TextField(max_length=2000, verbose_name='你想说什么'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='demand',
            field=models.TextField(max_length=2000, verbose_name='需求'),
        ),
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布时间'),
        ),
        migrations.DeleteModel(
            name='Activity_image',
        ),
    ]
