# Generated by Django 5.0.4 on 2025-03-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bushiba_app', '0010_activity_image1_activity_image2_activity_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='avatar',
            field=models.ImageField(default='user_avatar/default.png', upload_to='user_avatar/', verbose_name='头像'),
        ),
    ]
