# Generated by Django 5.0.4 on 2025-03-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bushiba_app', '0011_users_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='hobby',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='爱好'),
        ),
        migrations.AddField(
            model_name='users',
            name='motto',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='标签'),
        ),
    ]
