# Generated by Django 5.0.4 on 2025-03-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bushiba_app', '0012_users_hobby_users_motto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='motto',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='标签'),
        ),
    ]
