# Generated by Django 5.0.4 on 2025-03-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bushiba_app', '0013_alter_users_motto'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='nature',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='性格'),
        ),
    ]
