# Generated by Django 5.0.4 on 2025-03-26 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bushiba_app', '0014_users_nature'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='点赞时间')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bushiba_app.activity', verbose_name='动态')),
                ('liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bushiba_app.users', verbose_name='发布人')),
            ],
        ),
    ]
