# Generated by Django 5.0.4 on 2025-03-30 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bushiba_app', '0015_activitylike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylike',
            name='liker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bushiba_app.users', verbose_name='点赞人'),
        ),
        migrations.CreateModel(
            name='ActivityComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='评论发布时间')),
                ('text', models.TextField(max_length=200, verbose_name='评论内容')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bushiba_app.activity', verbose_name='动态')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bushiba_app.users', verbose_name='评论人')),
            ],
        ),
    ]
