# Generated by Django 5.0.4 on 2025-04-10 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bushiba_app', '0016_alter_activitylike_liker_activitycomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='点赞时间')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bushiba_app.activitycomment', verbose_name='动态评论')),
                ('liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bushiba_app.users', verbose_name='点赞人')),
            ],
        ),
    ]
