# Generated by Django 5.0.4 on 2025-04-26 14:20

import bushiba_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bushiba_app', '0017_activitycommentlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('title', models.TextField(max_length=20, verbose_name='标题')),
                ('description', models.TextField(max_length=1000, verbose_name='描述')),
                ('file', models.FileField(blank=True, null=True, upload_to=bushiba_app.models.rename_file_production, verbose_name='文件')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bushiba_app.users', verbose_name='作者')),
            ],
        ),
    ]
