# Generated by Django 5.0.4 on 2025-05-07 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bushiba_app', '0018_production'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='production_image/', verbose_name='需求图片')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bushiba_app.production', verbose_name='作品编号')),
            ],
        ),
    ]
