# Generated by Django 5.0.4 on 2025-05-10 14:46

import bushiba_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bushiba_app', '0019_productionimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=bushiba_app.models.production_image_path, verbose_name='需求图片'),
        ),
        migrations.CreateModel(
            name='ProductionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='评论发布时间')),
                ('text', models.TextField(max_length=200, verbose_name='评论内容')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bushiba_app.production', verbose_name='作品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bushiba_app.users', verbose_name='评论人')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionCommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='点赞时间')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bushiba_app.productioncomment', verbose_name='作品评论')),
                ('liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bushiba_app.users', verbose_name='点赞人')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='点赞时间')),
                ('liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bushiba_app.users', verbose_name='点赞人')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bushiba_app.production', verbose_name='动态')),
            ],
        ),
    ]
