# Generated by Django 5.0.4 on 2025-05-24 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bushiba_app', '0020_alter_productionimage_image_productioncomment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('text', models.TextField(max_length=2000, verbose_name='内容')),
                ('state', models.BooleanField(default=False, verbose_name='是否已读')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_messages', to='bushiba_app.users', verbose_name='发送人')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_messages', to='bushiba_app.users', verbose_name='接收人')),
            ],
        ),
    ]
