# Generated by Django 5.0.4 on 2025-06-01 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bushiba_app', '0021_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('text', models.TextField(max_length=50, verbose_name='留言')),
                ('state', models.BooleanField(default=False, verbose_name='是否同意')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_friend', to='bushiba_app.users', verbose_name='发送人')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_friend', to='bushiba_app.users', verbose_name='接收人')),
            ],
        ),
    ]
