# Generated by Django 5.0.4 on 2025-06-02 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bushiba_app', '0022_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='text',
        ),
    ]
